# Generated by Django 4.1.4 on 2023-07-08 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='lfname',
            new_name='lname',
        ),
    ]
